### ISSUE TITLE
How to translate this theme ?

### ISSUE THREAD

**Issue by marmotz** [andersnoren/hemingway#1]
Hi,

first of all, thank you for creating this beautiful theme.

But I can't find any file to add a French translation for my blog.

Could you explain to me how to translate this theme?

**Comment by andersnoren** [comment]
@marmotz Glad you like it! You can update the French translation of the theme on WordPress.org. Once it has enough translated strings, it will be made available to all Hemingway users with French installs. You can find the translation tool here: https://translate.wordpress.org/projects/wp-themes/hemingway/

You can also use a theme translation plugin like WPML to translate the strings on your specific WordPress installation.

**Comment by marmotz** [comment]
Thanks @andersnoren but i used TranslatePress plugin
